OPENAI_MODEL = "gpt-4-1106-preview"
OPENAI_VISION_MODEL = "gpt-4-vision-preview"
OPENAI_WHISPER_MODEL = "whisper-1"
OPENAI_DALL_E = "dall-e-3"
GOOGLE_MODEL = "gemini-pro"
GOOGLE_VISION_MODEL = "gemini-pro-vision"